spring:
  application:
    name: "bizscan"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always


naver:
  ad:
    base-url: https://api.searchad.naver.com
    api-key: ${NAVER_AD_API_KEY}
    secret-key: ${NAVER_AD_SECRET_KEY}
    customer-id: ${NAVER_AD_CUSTOMER_ID}

kakao:
  api:
    key: ${KAKAO_API_KEY}
    url: "https://dapi.kakao.com/v2/local/search/address.json"

ai:
  fastapi:
    base-url: http://127.0.0.1:8000
    analysis-path: /ai-analysis
    diagnosis-path: /ai-diagnosis