services:
  app:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:${IMAGE_TAG}
    container_name: bizscan-app-${PROFILE:-dev}
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE:-dev}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PW: ${DB_PW}
      TZ: Asia/Seoul
      NAVER_AD_API_KEY: ${NAVER_AD_API_KEY}
      NAVER_AD_SECRET_KEY: ${NAVER_AD_SECRET_KEY}
      NAVER_AD_CUSTOMER_ID: ${NAVER_AD_CUSTOMER_ID}
      KAKAO_REST_API_KEY: ${KAKAO_REST_API_KEY}
      KAKAO_API_KEY: ${KAKAO_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
    #      REDIS_PASS: ${REDIS_PASS}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - bizscan-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    expose:
      - "6379"
    environment:
      TZ: Asia/Seoul
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save 60 1000
      --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - bizscan-network
    restart: unless-stopped

  dozzle:
    image: amir20/dozzle:latest
    ports:
      - "9999:8080"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - bizscan-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - bizscan-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - TZ=Asia/Seoul
      - GF_SERVER_ROOT_URL=${GRAFANA_ROOT_URL}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    depends_on:
      - prometheus
    networks:
      - bizscan-network
    restart: unless-stopped

networks:
  bizscan-network:
    driver: bridge

volumes:
  redis-data:
  prometheus-data:
  grafana-data: